# Generated by Django 4.0.2 on 2022-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unversity_name', models.CharField(choices=[('Al_azhar', 'Al_azhar'), ('Islamic_Unversity', 'Islamic_Unversity')], max_length=50)),
            ],
        ),
    ]
