# Generated by Django 4.0.2 on 2022-02-25 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finance_name', models.CharField(default='file name', max_length=60)),
                ('finance_reports', models.FileField(upload_to='finance_reports')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('Finance_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
