# Generated by Django 4.0.2 on 2022-02-25 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unversity', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('living_place', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images_of_students')),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_graduation', models.PositiveIntegerField(blank=True, null=True)),
                ('achieved_hours', models.PositiveIntegerField(default='40')),
                ('still_hours', models.IntegerField(default='100')),
                ('Cumulative_average', models.IntegerField(default='80')),
                ('seimester_average', models.IntegerField(default='80')),
                ('price_of_hour', models.IntegerField(blank=True, null=True)),
                ('unversity_id_number', models.BigIntegerField(blank=True, null=True)),
                ('comment_about_behavoir', models.TextField(blank=True, max_length=50, null=True)),
                ('unversity', models.ForeignKey(default='Al_azhar', on_delete=django.db.models.deletion.CASCADE, to='Unversity.unversity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
